export const optionsCategory = [
    { value: "math", label: "Математика" },
    { value: "english", label: "Английский" },
    { value: "physics", label: "Физика" },
    { value: "chemistry", label: "Химия" },
    { value: "programming", label: "Программирование" },
];

export const optionsCity = [
    { value: "moscow", label: "Москва" },
    { value: "spb", label: "Санкт-Петербург" },
    { value: "magas", label: "Магас" },
    { value: "novosibirsk", label: "Новосибирск" },
    { value: "ekaterinburg", label: "Екатеринбург" },
    { value: "nizhny_novgorod", label: "Нижний Новгород" },
    { value: "kazan", label: "Казань" },
    { value: "chelyabinsk", label: "Челябинск" },
    { value: "omsk", label: "Омск" },
    { value: "samara", label: "Самара" },
    { value: "rostov-on-don", label: "Ростов-на-Дону" },
    { value: "ufa", label: "Уфа" },
    { value: "krasnoyarsk", label: "Красноярск" },
    { value: "perm", label: "Пермь" },
    { value: "voronezh", label: "Воронеж" },
    { value: "volgograd", label: "Волгоград" },
    { value: "krasnodar", label: "Краснодар" },
    { value: "saratov", label: "Саратов" },
    { value: "tyumen", label: "Тюмень" },
    { value: "toljatti", label: "Тольятти" },
    { value: "barnaul", label: "Барнаул" },
    { value: "ulyanovsk", label: "Ульяновск" },
    { value: "izhevsk", label: "Ижевск" },
    { value: "yaroslavl", label: "Ярославль" },
    { value: "khabarovsk", label: "Хабаровск" },
    { value: "vladivostok", label: "Владивосток" },
    { value: "krasnoyarsk", label: "Красноярск" },
    { value: "makhachkala", label: "Махачкала" },
    { value: "tomsk", label: "Томск" },
    { value: "orenburg", label: "Оренбург" },
    { value: "novokuznetsk", label: "Новокузнецк" },
    { value: "ryazan", label: "Рязань" },
    { value: "astrakhan", label: "Астрахань" },
    { value: "naberezhnye_chelny", label: "Набережные Челны" },
    { value: "penza", label: "Пенза" },
    { value: "lipetsk", label: "Липецк" },
    { value: "kirov", label: "Киров" },
    { value: "cheboksary", label: "Чебоксары" },
    { value: "tula", label: "Тула" },
    { value: "kaliningrad", label: "Калининград" },
    { value: "bryansk", label: "Брянск" },
    { value: "ivanovo", label: "Иваново" },
    { value: "magnitogorsk", label: "Магнитогорск" },
    { value: "tambov", label: "Тамбов" },
    { value: "engels", label: "Энгельс" },
    { value: "severodvinsk", label: "Северодвинск" },
    { value: "podolsk", label: "Подольск" },
    { value: "taganrog", label: "Таганрог" },
    { value: "syzran", label: "Сызрань" },
    { value: "sterlitamak", label: "Стерлитамак" },
    { value: "khimki", label: "Химки" },
    { value: "balashikha", label: "Балашиха" },
    { value: "armavir", label: "Армавир" },
    { value: "zelenograd", label: "Зеленоград" },
    { value: "nizhnekamsk", label: "Нижнекамск" },
    { value: "stavropol", label: "Ставрополь" },
    { value: "korolev", label: "Королев" },
    { value: "abakan", label: "Абакан" },
    { value: "mytishchi", label: "Мытищи" },
    { value: "yaroslavl", label: "Ярославль" },
    { value: "krasnoturinsk", label: "Краснотурьинск" },
    { value: "elektrostal", label: "Электросталь" },
    { value: "pskov", label: "Псков" },
    { value: "velikiye_luki", label: "Великие Луки" },
    { value: "kursk", label: "Курск" },
    { value: "ivanovo", label: "Иваново" },
    { value: "kaluga", label: "Калуга" },
    { value: "veliky_novgorod", label: "Великий Новгород" },
    { value: "smolensk", label: "Смоленск" },
    { value: "tver", label: "Тверь" },
    { value: "rybinsk", label: "Рыбинск" },
    { value: "bratsk", label: "Братск" },
    { value: "belgorod", label: "Белгород" },
    { value: "kurgan", label: "Курган" },
    { value: "kaliningrad", label: "Калининград" },
    { value: "velikiy_novgorod", label: "Великий"},
]